open = "1H"
meaning = "5-card major"
notes = ["Note that all 17+ hands go through Gazzilli.", "Priorities. Responder with a weak hand should first look to bid a 7+ suit of their own then two of opener's major with 2+ support finally a shorter suit or three-suited hand."]

[pass.1NT]
meaning = "Up to poor 12, NF"
notes = ["After 1H P 1NT X, redouble now shows a 17+ hand and other bids or normal including 2C."]

[pass.1NT.pass.2C]
meaning = "Gazzilli (Weak with clubs or 17+ HCP. explained below)"
notes = ["If opener rebids 3NT after Gazzilli it shows 18-19 balanced, 5M332. 2NT rebid shows 15-17 balanced with 5M332 and the major suit is good.", "If defenders double Gazzilli 2C responder passes showing OK clubs and redoubles to show 8+.", "If defenders double 2D after Gazzilli then redouble is 16+ pass shows weak hand with 3 diamonds.", "If they overcall Gazzilli then we bid normally."]

[pass.1NT.pass.2C.pass.2D]
meaning = "8+ HCP with any shape (see below)"
rebid = "Opener either rebids their major showing the weak option so 5+ hearts and 4+ clubs 11-14 any other bid 17+ GF."

[pass.1NT.pass.2C.pass.2H]
meaning = "5-7 HCP with 2+ hearts"
rebid = "They have a tight range of hands and opener is usually well placed to pick the contract or invite."

[pass.1NT.pass.2C.pass.2NT]
meaning = "5-7 HCP with 5+ clubs and 5+ diamonds"

[pass.1NT.pass.2C.pass.2S]
meaning = "5-7 HCP with a 3 suited hand with short hearts"

[pass.1NT.pass.2C.pass.3C]
meaning = "5-7 HCP with 6+ clubs"

[pass.1NT.pass.2C.pass.3D]
meaning = "5-7 HCP with 6+ diamonds"

[pass.1NT.pass.2D]
meaning = "11-16 HCP with 3+ diamonds"

[pass.1NT.pass.2H]
meaning = "11-16 HCP with 6+ hearts"

[pass.1NT.pass.2NT]
meaning = "14-16 HCP with 6 hearts and 4+ minor."
notes = ["Opener has shown a 6-4 shape with a better than minimum hand."]

[pass.1NT.pass.2NT.pass.3C]
meaning = "pass or correct"

[pass.1NT.pass.2NT.pass.3D]
meaning = "game forcing asking for the minor"

[pass.1NT.pass.2NT.pass.3D.pass.3H]
meaning = "should show clubs"

[pass.1NT.pass.2NT.pass.3D.pass.3S]
meaning = "should show diamonds"

[pass.1NT.pass.2NT.pass.3H]
meaning = "to play"

[pass.1NT.pass.2S]
meaning = "14-16 HCP with 6 hearts and 5 spades"

[pass.1NT.pass.3C]
meaning = "14-16 HCP with 5 hearts and 5 clubs"

[pass.1NT.pass.3D]
meaning = "14-16 HCP with 5 hearts and 5 diamonds"

[pass.1NT.pass.3H]
meaning = "14-16 HCP with 6+ hearts (great suit)"

[pass.1S]
meaning = "Natural, F1"

[pass.1S.pass.1NT]
meaning = "11-14 HCP balanced."

[pass.1S.pass.2C]
meaning = "Gazzilli (Weak with clubs or 17+ HCP. explained below)"
notes = ["If opener rebids 3NT after Gazzilli it shows 18-19 balanced, 5M332. 2NT rebid shows 15-17 balanced with 5M332 and the major suit is good.", "If defenders double Gazzilli 2C responder passes showing OK clubs and redoubles to show 8+.", "If defenders double 2D after Gazzilli then redouble is 16+ pass shows weak hand with 3 diamonds.", "If they overcall Gazzilli then we bid normally."]

[pass.1S.pass.2C.pass.2D]
meaning = "8+ HCP with any shape"
rebid = "Opener either rebids their major showing the weak option so 5+ hearts and 4+ clubs 11-14 any other bid 17+ GF."

[pass.1S.pass.2C.pass.2H]
meaning = "5-7 HCP and 2+ hearts"
rebid = "They have a tight range of hands and opener is usually well placed to pick the contract or invite."

[pass.1S.pass.2C.pass.2NT]
meaning = "5-7 HCP with a 3 suited hand with short hearts"
rebid = "As for 2H"

[pass.1S.pass.2C.pass.2S]
meaning = "8-10 HCP with 6+ spades"

[pass.1S.pass.2C.pass.3C]
meaning = "5-7 HCP with 6+ clubs"
rebid = "As for 2H"

[pass.1S.pass.2C.pass.3D]
meaning = "5-7 HCP and 6+ diamonds"
rebid = "As for 2H"

[pass.1S.pass.2D]
meaning = "11-16 HCP with 3+ diamonds"

[pass.1S.pass.2H]
meaning = "11-16 HCP with 6+ hearts"

[pass.1S.pass.2NT]
meaning = "14-16 HCP with 6 hearts and 4+ minor"
notes = ["Opener has shown a 6-4 shape with a better than minimum hand."]

[pass.1S.pass.2NT.pass.3C]
meaning = "pass or correct"

[pass.1S.pass.2NT.pass.3D]
meaning = "game forcing asking for the minor"

[pass.1S.pass.2NT.pass.3D.pass.3H]
meaning = "should show clubs"

[pass.1S.pass.2NT.pass.3D.pass.3S]
meaning = "should show diamonds"

[pass.1S.pass.2NT.pass.3H]
meaning = "to play"

[pass.1S.pass.2S]
meaning = "14-16 HCP with 5+ hearts and 4+ spades"

[pass.1S.pass.3C]
meaning = "14-16 HCP with 5 hearts and 5 clubs"

[pass.1S.pass.3D]
meaning = "14-16 HCP with 5 hearts and 5 diamonds"

[pass.1S.pass.3H]
meaning = "14-16 HCP with 6+ hearts (great suit)"

[pass.2NT]
meaning = "4-card raise, GF"

[pass.2NT.pass.3C]
meaning = "Any minimum"

[pass.2NT.pass.3C.pass.3D]
meaning = "Asks for shortage"

[pass.2NT.pass.3C.pass.3D.pass."3H/S/NT "]
meaning = "Shortage in C/D/oM respectively"

[pass.2NT.pass.3C.pass.3D.pass."4C/D "]
meaning = "Natural, good suit"

[pass.2NT.pass.3C.pass.3D.pass.4H]
meaning = "Nothing else"

[pass.2NT.pass.3C.pass.3H]
meaning = "5+ cards"

[pass.2NT.pass.3C.pass.3S]
meaning = "cue"
notes = ["3NT - start cueing; serious slam interest"]

[pass.2NT.pass.3C.pass."4C/D "]
meaning = "cues"

[pass.2NT.pass.3C.pass.4H]
meaning = "nothing else"

[pass.2NT.pass.3D]
meaning = "Balanced, extras"

[pass.2NT.pass.3D.pass.3H]
meaning = "slam interest"

[pass.2NT.pass.3D.pass.3NT]
meaning = "serious slam try"

[pass.2NT.pass.3D.pass.3S]
meaning = "cue"

[pass.2NT.pass.3D.pass."4C/D "]
meaning = "cue"

[pass.2NT.pass.3D.pass.4H]
meaning = "Nothing else, barely GF"

[pass.2NT.pass."3H/S/NT "]
meaning = "Shortage in C/D/oM and extras"

[pass.2NT.pass."4C/D "]
meaning = "Good side suit, usually 5 cards and extras"

[pass.3C]
meaning = "Good 9 to poor 12 points, 3 card support"
rebid = "3 level suit bids below agreed suit are game tries and show values in the suit bid."

[pass.3D]
meaning = "9-11 points, 4 card support"
rebid = "3 level suit bids below agreed suit are game tries and show values in the suit bid."

[pass."3S/4C/4D "]
meaning = "Double jumps are splinters with 9-12 pts (stronger hands bid 2NT to GF)."
