open = "1S"
meaning = "5-card major"
notes = ["Note that all 17+ hands go through Gazzilli.", "Priorities. Responder with a weak hand should first look to bid a 7+ suit of their own then two of opener's major with 2+ support finally a shorter suit or three-suited hand."]

[pass.1NT]
meaning = "Up to poor 12, NF"

[pass.1NT.pass.2C]
meaning = "Gazzilli (Weak with clubs or 17+ HCP. explained below)"
notes = ["If opener rebids 3NT after Gazzilli it shows 18-19 balanced, 5M332. 2NT rebid shows 15-17 balanced with 5M332 and the major suit is good.", "If defenders double Gazzilli 2C responder passes showing OK clubs and redoubles to show 8+.", "If defenders double 2D after Gazzilli then redouble is 16+ pass shows weak hand with 3 diamonds.", "If they overcall Gazzilli then we bid normally."]

[pass.1NT.pass.2C.pass.2D]
meaning = "8+ HCP with any shape"
rebid = "Opener either rebids their major showing the weak option so 5+ spades and 4+ clubs 11-14 any other bid 17+ GF."

[pass.1NT.pass.2C.pass.2H]
meaning = "5-7 HCP with 5+ hearts"
rebid = "They have a tight range of hands and opener is usually well placed to pick the contract or invite."

[pass.1NT.pass.2C.pass.2NT]
meaning = "5-7 HCP with a 3 suited hand with short spades"
notes = ["3C shows 5-7 HCP with 6+ clubs", "3D shows 5-7 HCP with 6+ diamonds"]

[pass.1NT.pass.2C.pass.2S]
meaning = "5-7 HCP with 2+ spades"

[pass.1NT.pass.2D]
meaning = "11-16 HCP with 3+ diamonds"

[pass.1NT.pass.2H]
meaning = "11-16 HCP with 5+ spades 4+ hearts"

[pass.1NT.pass.2NT]
meaning = "14-16 HCP with 6 spades and 4+ minor."
notes = ["Opener has shown a 6-4 shape with a better than minimum hand."]

[pass.1NT.pass.2NT.pass.3C]
meaning = "pass or correct"

[pass.1NT.pass.2NT.pass.3D]
meaning = "game forcing asking for the minor"

[pass.1NT.pass.2NT.pass.3D.pass.3H]
meaning = "should show clubs"

[pass.1NT.pass.2NT.pass.3D.pass.3S]
meaning = "should show diamonds"

[pass.1NT.pass.2NT.pass.3H]
meaning = "to play"

[pass.1NT.pass.2S]
meaning = "14-16 HCP with 6+ spades"

[pass.1NT.pass.3C]
meaning = "14-16 HCP with 5 spades and 5 clubs"

[pass.1NT.pass.3D]
meaning = "14-16 HCP with 5 spades and 5 diamonds"

[pass.1NT.pass.3H]
meaning = "14-16 HCP with 5+ spades and 5+ hearts"

[pass.1NT.pass.3S]
meaning = "14-16 HCP with 6+ spades (great suit)"
